sudo: required
dist: bionic

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full pandoc latexmk

before_script:
  - chmod +x ./travis/_deploy.sh

script:
  - make clean
  - make all
  - cd output && mv main.htm index.html && cd ../
  - ./travis/_deploy.sh


