sudo: required
dist: bionic
language: node_js
node_js:
  - node

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full pandoc latexmk pdf2svg pandoc latexmk
  - npm -g install mathjax-node-page

before_script:
  - chmod +x ./travis/_make4ht.sh
  - chmod +x ./travis/_deploy.sh

script:
  - ./travis/_make4ht.sh
  - echo make4ht --version
  - make clean
  - make all
  - cd output/html && cd ../../
  - ./travis/_deploy.sh