# Probability and Counting

## Counting
  
###

__Intuition__

Imagine eleven empty slots to place the letters into. 

How many ways are there to place the four $I$-s into the slots? For each placement of $I$s, can we figure out the number of ways to place the remaining letters into the $7$ empty slots?

<details>
  <summary>__Solution__</summary>
  
We have one $M$, four $I$-s, four $S$-s, and two $P$-s. There are ${11 \choose 4}$ ways to place the $I$-s, ${7 \choose 4}$ ways to place $S$-s, ${3 \choose 2}$ ways to place the $P$-s, and ${1 \choose 1}$ ways to place the $M$.

  $$ {11 \choose 4} \times {7 \choose 4} \times {3 \choose 2} \times {1 \choose 1} $$
</details>

###

a.\ __Intuition__

If the first digit can't be $0$ or $1$, how many choices are we left with for the first digit? For each choice of first digit, how many choices do we have for the remaining six digits?

<details>
  <summary>__Solution__</summary>
  
If the first digit can't be $0$ or $1$, we have eight choices for the first digit - $2$ to $9$. The remaining six digits can be anything from $0$ to $9$. Hence, the solution is
  $$ 8 \times 10^{6} $$
</details>

b.\ __Intuition__ 

How many phone numbers start with $911$? 

Can we use the answer from the previous part to find the desired quantity? 

<details>
  <summary>__Solution__</summary>

We can subtract the number of phone numbers that start with $911$ from the total number of phone numbers we found in the previous part. 

If a phone number starts with $911$, it has ten choices for each of the remaining four digits.

  $$ 8 \times 10^{6} - 10^{4} $$
</details>

### 

a.\ __Intuition__

How many choices of restaurants does Fred have on Monday?

Once Fred attends a restaurant on Monday, how many choices of restaurants does he have for the remainder of the week?

<details>
  <summary>__Solution__</summary>

Fred has $10$ choices for Monday, $9$ choices for Tuesday, $8$ choices for Wednesday, $7$ choices for Thursday and $6$ choices for Friday.

  $$ 10 \times 9 \times 8 \times 7 \times 6 $$
</details>

b.\ __Intution__

We are told that Fred will not attend a restaurant he went to the previous day, but can he go to a restaurant he went to two or more days ago?

<details>
  <summary>__Solution__</summary>

For the first restaurant, Fred has $10$ choices. For all subsequent days, Fred has $9$ choices, since the only restriction is that he doesn't want to eat at the restaurant he ate at the previous day.

  $$ 10 \times 9^{4} $$
</details>

###

a.\ __Intuition__

How many matches are there in a _round-robin_ tournament? 

How many outcomes are possible for each match?

<details>
  <summary>__Solution__</summary>

There are ${n \choose 2}$ matches. 

For a given match, there are two outcomes. Each match has two possible outcomes. We can use the multiplication rule to count the total possible outcomes.

  $$ 2^{{n \choose 2}} $$
</details>

b.\ __Intuition__

How many opponents will every player play against? 

How many times will a given pair of players face each other?

<details>
  <summary>__Solution__</summary>

Since every player plays every other player exactly once, the number of games is the number of ways to pair up $n$ people.

  $$ {n \choose 2} $$
</details>

###

a.\ __Intuition__

How many players are left by the end of a round compared to the number of players at the start of the round?

How many rounds need to pass for a single player to be left standing?

<details>
  <summary>__Solution__</summary>

By the end of each round, half of the players participating in the round are eliminated. So, the problem reduces to finding out how many times the number of players can be halved before a single player is left.

  The number of times $N$ can be divided by two is $$\log_{2}{N}$$
</details>

b.\ __Intuition__

Suppose there are $N_{r}$ players at the start of round $r$. If every player plays exactly one game, how many games will be played in round $r$?

<details>
  <summary>__Solution__</summary>

The number of games in a given round is $\frac{N_{r}}{2}$. We can sum up these values for all the rounds.

  \begin{equation} 
  \begin{split}
   f(N) & = \frac{N}{2} + \frac{N}{4}  + \frac{N}{8} + \dots + \frac{N}{2^{\log_{2}{N}}}\\
   & =N \sum_{i=0}^{\log_{2}{N}} \frac{1}{2^{i}}\\
   & =N \times \frac{N-1}{N}\\
   & =N-1
  \end{split}
  \end{equation} 
</details>

c.\ __Intuition__

How many players need to be eliminated before the tournament is over?

How many players are eliminated as a result of a single match?

<details>
  <summary>__Solution__</summary>

Tournament is over when a single player is left. Hece, $N-1$ players need to be eliminated. As a result of a match, exactly one player is eliminated. Hence, the number of matches needed to eliminate $N-1$ people is

  $$ N-1 $$
</details>

### 

__Intuition__

How many ways can we match up twenty chess players if we don't care about who plays with white and who plays with black pieces?

Can we use the answer from the previous part to find the desired quantity?

<details>
  <summary>__Solution__</summary>

There are ${20 \choose 2}$ ways to pair up twenty chess players. For each pairing, we can first let player $A$ play with whites, then let player $B$ play with whites. Thus, for each of the ${20 \choose 2}$ pairs, we have $2$ matches for a total of

  $$ {20 \choose 2} \times 2 $$
matches.

</details>

###

a.\ __Intuition__

How many ways are there to assign three wins to player $A$? 

Out of the remaining four games, how many ways are there to assign two draws and two losses to $A$?

<details>
  <summary>__Solution__</summary>

There are ${7 \choose 3}$ ways to assign three wins to player $A$. For a specific combination of three games won by $A$, there are ${4 \choose 2}$ ways to assign two draws to $A$. There is only one way to assign two losses to $A$ from the remaining two games, namely, $A$ losses both games.

  $$ {7 \choose 3} \times {4 \choose 2} \times {2 \choose 2} $$
</details>

b.\ __Intuition__

Can $A$ get $4$ points if $A$ never wins? What if $A$ wins more than $4$ games?

List the possible outcomes of games that award $4$ points to $A$.

<details>
  <summary>__Solution__</summary>
  
  If $A$ were to draw every game, there would need to be at least $8$ games for $A$ to obtain $4$ points, so $A$ has to win at least $1$ game. Similarly, if $A$ wins more than $4$ games, they will have more than $4$ points.
  
  Case 1: $A$ wins $1$ game and draws $6$.
  
  This case amounts to selecting $1$ out of $7$ for $A$ to win and assigning a draw for the other $6$ games. Hence, there are $7$ possibilities.
    
  Case 2: $A$ wins $2$ games and draws $4$.
  
  There are ${7 \choose 2}$ ways to assign $2$ wins to $A$. For each of them, there are ${5 \choose 4}$ ways to assign four draws to $A$ out of the remaining $5$ games. Player $B$ wins the remaining game. The total number of possibilites for this case is ${7 \choose 2} \times {5 \choose 4}$.
  
  Case 3: $A$ wins $3$ games and draws $2$.
  
  There are ${7 \choose 3}$ ways to assign $3$ wins to $A$. For each of them, there are ${4 \choose 2}$ ways to assign two draws to $A$ out of the remaining $4$ games. $B$ wins the remaining $2$ games. The total number of possibilites for this case is ${7 \choose 3} \times {4 \choose 2}$.
  
  Case 4: $A$ wins $4$ games and loses $3$.
  
  There are ${7 \choose 4}$ ways to assign $4$ wins to $A$. $B$ wins the remaining $3$ games.
  The total number of possibilites for this case is ${7 \choose 4}$.
  
  Summing up the number of possibilities in each of the cases we get
  
  $$ {7 \choose 1} + {7 \choose 2} \times {5 \choose 4} + {7 \choose 3} \times {4 \choose 2} + {7 \choose 4} $$
</details>

c.\ __Intuition__

Given the final score of $4$ to $3$ and the fact that the match will end if either of the players reaches $4$ points, could $B$ have been the player to win the last game?

Suppose $A$ wins the last game. Could $A$ have won only $1$ game out of the first $6$?

Count the number of possibilites for the case when $A$ wins the last game and the number of possibilities for the case when $A$ draws the last game.

<details>
  <summary>__Solution__</summary>
  
  If $B$ were to win the last game, that would mean that $A$ had already obtained $4$ points prior to the last game, so the last game would not be played at all. Hence, $B$ could not have won the last game.
  
  Case 1: $A$ wins $3$ out of the first $6$ games and wins the last game.
  
  There are ${6 \choose 3}$ ways to assign $3$ wins to $A$ out of the first $6$ games. The other $3$ games end in a draw. The number of possibilities then is ${6 \choose 3}$.
  
  Case 2: $A$ wins $2$ and draws $2$ out of the first $6$ games and wins the last game.
  
  There are ${6 \choose 2}$ ways to assign $2$ wins to $A$ out of the first $6$ games. From the $4$ remaining games, there are ${4 \choose 2}$ ways to assign $2$ draws. The remaining $2$ games are won by $B$. The number of possibilities is ${6 \choose 2} \times {4 \choose 2}$.
  
  Case 3: The last game ends in a draw.
  
  This case implies that $A$ had $3.5$ and $B$ had $2.5$ points by the end of game $6$.
  
  Case 3.1: $A$ wins $3$ and draws $1$ out of the first $6$ games.
  
  There are ${6 \choose 3}$ ways to assign $3$ wins to $A$ out of the first $6$ games. There are ${3 \choose 1}$ ways to assign a draw out of the remaining $3$ games. $B$ wins the other $2$ games. The number of possibilities is ${6 \choose 3} \times {3 \choose 1}$.
  
  Case 3.2: $A$ wins $2$ and draws $3$ out of the first $6$ games.
   
  There are ${6 \choose 2}$ ways to assign $2$ wins to $A$ out of the first $6$ games. There are ${4 \choose 3}$ ways to assign $3$ draws out of the remaining $4$ games. $B$ wins the remaining game. The number of possibilities is ${6 \choose 2} \times {4 \choose 3}$.
  
  Case 3.3: $A$ wins $1$ and draws $5$ of the first $6$ games.
  
  There are ${6 \choose 1}$ ways to assign a win to $A$ out of the first $6$ games.
  
  The total number of possibilities then is
  
  $$ {6 \choose 3} + {6 \choose 2} \times {4 \choose 2} + {6 \choose 3} \times {3 \choose 1} + {6 \choose 2} \times {4 \choose 3} + {6 \choose 1}$$
</details>

### 

Solution is provided by the author.

### 

Solution is provided by the author.

###

a.\ __Intuition__
  
How many choices are there if the student takes only one statistics course? What about two statistics courses?

<details>
  <summary>__Solution__</summary>
  
  Case 1: Student takes exactly one statistics course.
  
  There are $5$ choices for the statistics course. There are ${15 \choose 6}$ choices of selecting $6$ non-statistics courses.
  
  Case 2: Student takes exactly two statistics courses.
  
  There are ${5 \choose 2}$ choices for the two statistics course. There are ${15 \choose 5}$ choices of selecting $5$ non-statistics courses.
  
  Case 3: Student takes exactly three statistics courses.
  
  There are ${5 \choose 3}$ choices for the three statistics course. There are ${15 \choose 4}$ choices of selecting $4$ non-statistics courses.
  
  Case 4: Student takes exactly four statistics courses.
  
  There are ${5 \choose 4}$ choices for the four statistics course. There are ${15 \choose 3}$ choices of selecting $3$ non-statistics courses.
  
  Case 5: Student takes all the statistics courses.
  
  There are ${15 \choose 2}$ choices of selecting $2$ non-statistics courses.
  
  So the total number of choices is
  
  $${5 \choose 1} \times {15 \choose 6} + {5 \choose 2} \times {15 \choose 5} + {5 \choose 3} \times {15 \choose 4} + {5 \choose 4} \times {15 \choose 3} + {5 \choose 5} \times {15 \choose 2}$$
  
</details>

b.\ __Intuition__

Would ${5 \choose 1} \times {19 \choose 6}$ overcount any choices?

<details>
  <summary>__Solution__</summary>
  
  It is true that there are ${5 \choose 1}$ ways to select a statistics course, and ${19 \choose 6}$ ways to select $6$ more courses from the remaining $19$ courses, but this procedure results in overcounting.
  
  For example, consider the following two choices.
  
  a. STAT110, STAT134, History 124, English 101, Calculus 102, Physics 101, Art 121
  b. STAT134, STAT110, History 124, English 101, Calculus 102, Physics 101, Art 121
  
  Notice that both are selections the same $7$ courses.
  
</details>

###

a.\ __Intuition__

To specify a function, we need to assign an output to every input. How many ways are there to do this?

<details>
  <summary>__Solution__</summary>
  
  Each of the $n$ inputs has $m$ choices for an output, resulting in $$m^{n}$$ possible functions.
</details>

b.\ __Intuition__

A function is _one-to-one_ if it maps unique inputs to unique outputs. Suppose $n < m$. Can a function be one-to-one?

<details>
  <summary>__Solution__</summary>
  
  If $n < m$, at least two inputs will be mapped to the same output, so no one-to-one function is possible. 
  
  If $n \geq m$, the first input has $m$ choices, the second input has $m - 1$ choices, and so on. The total number of one-to-one functions then is $$m(m-1)(m-2)\dots(m-n+1)$$
</details>

###

a.\ __Intuition__

How many ways are there to select $13$ cards out of a standard deck?

<details>
  <summary>__Solution__</summary>
  
  $${52 \choose 13}$$
</details>

b.\ __Intuition__

How many ways are there to break a standard deck into $4$ groups of size $13$? Can we use this result to get the desired quantity?

<details>
  <summary>__Solution__</summary>
  
  The number of ways to break $52$ cards into $4$ groups of size $13$ is $$\frac{{52 \choose 13}{39 \choose 13}{26 \choose 13}{13 \choose 13}}{4!}$$.
  
  The reason for dividision by $4!$ is that all permutations of specific $4$ groups describe the same way to group $52$ cards.
  
  Since we do care about the order of the $4$ groups, we should not divide by ${4!}$. The final answer then is 
  $${52 \choose 13}{39 \choose 13}{26 \choose 13}{13 \choose 13}$$
</details>

c.\ __Intuition__

Does dealing $13$ cards to player $A$ change the number of possible hands $B$ could get?

<details>
  <summary>__Solution__</summary>
  
  The key is to notice that the sampling is done _without replacement_. ${52 \choose 13}^{4}$ assumes that all four players have ${52 \choose 13}$ choices of hands available to them. This would be true if sampling was done _with replacement_.
  
</details>

###

__Intuition__

Why is the answer not ${520 \choose 10}$? 

Why is the answer not $520^{10}$?

<details>
  <summary>__Solution__</summary>
  
  The problem amounts to sampling with replacement where order does not matter, since having $10$ copies of each card amounts to replacing the card. This is done using the Bose-Einstein method.
  
  Thus, the answer is $${52 + 10 - 1 \choose 10} = {61 \choose 10}$$
</details>

###

__Intuition__

How many possibilities are there for a small pizza? What about a medium pizza? 

Note that ordering a Small Vegetarian and a Large Pepperoni is the same as ordering a Large Pepperoni and a Small Vegetarian.

<details>
  <summary>__Solution__</summary>
  
  There are $4$ choices for sizes and $9$ choices for toppings for a total of $36$ possibilities for a single pizza. Since we are ordering $2$ pizzas, we get $36^{2}$ possibilities. However, this result overcounts the desired quantity by a factor of $2$, since
  
  1. Small Vegetarian, Large Pepperoni
  2. Large Pepperoni, Small Vegetarian
  
  describe the same order. The number of possibilities then is $$\frac{36^{2}}{2}$$
  
</details>

## Story Proofs

###

Solution provided by the author

###

Solution provided by the author

###

__Intuition__

How many ways are there to sample $n$ objects from a set of $2n$?

Can we break up the original set into two sets of size $n$ and sample from both sets?

<details>
  <summary>__Solution__</summary>
  
  ${2n \choose n}$ counts the number of ways to sample $n$ objects from a set of $2n$. Instead of sampling from the whole set, we can break the set into two sets of size $n$ each. Then, we have to sample $n$ objects in total from both sets. 
  
  We can sample all $n$ objects from the first set, or $1$ object from the first set and $n-1$ objects from the second set, or $2$ objects from the first set and $n-2$ objects from the second set and so on.
  
  There are ${n \choose n}$ ways to sample all $n$ objects from the first set, ${n \choose 1} {n \choose n-1}$ ways to sample $1$ object from the first set and $n-1$ objects from the second set, ${n \choose 2} {n \choose n-2}$ ways to sample $2$ objects from the first set and $n-2$ objects from the second set. The pattern is clear $$ \sum_{k=0}^{n} {n \choose k} {n \choose n-k} = \sum_{k=0}^{n} {n \choose k}^{2}$$
  
</details>

###

__Intuition__

If a person is selected for a committee chair, how many ways are there to select the remaining members?

If $m$ members are selected from the first group and $n-m$ members are selected from the second group, how many ways are there to assign a chair?

<details>
  <summary>__Solution__</summary>
  
  Consider the right hand side of the equation. Since a committe chair can only be selected from the first group, there are $n$ ways to choose them. Then, for each choice of a committee chair, there are ${2n-1 \choose n-1}$ ways to choose the remaining members. Hence, the total number of committees is $n{2n-1 \choose n-1}$.
  
  Now consider the left side of the equation. Suppose we pick $k$ people from the first group and $n-k$ people from the second group, then there are $k$ ways to assign a chair from the members of the first group we have picked. $k$ can range from $1$ to $n$ giving us a total of $\sum_{k=1}^{n} k{n \choose k}{n \choose n-k} = \sum_{k=1}^{n} k{n \choose k}^{2}$ possible committees.
  
  Since, both sides of the equation count the same thing, they are equal.
</details>

###

__Intuition__

Expanding on the hint provided by the author, think of elements in the subsets as ordered from lowest to largest. What is the smallest and the largest values a middle element can have?

If the middle element is $k+1$, how many choices do we have for the left half of the subset? What about the right half?

<details>
  <summary>__Solution__</summary>
  
  Since the subsets have size $5$, a middle element can range from $3$ to $n+1$. Let us label middle elements as $k+1$. Then, there are ${k \choose 2}$ choises of elements for the left half of a subset and ${n+3-(k+1) \choose 2} = {n+2-k \choose 2}$ choices for the right half.
  
  Taking the sum as $k+1$ ranges from $3$ to $n+1$, we get the desired result.
</details>

###

Solution provided by the author

###

a.\ __Intuition__

Suppose there are $n+1$ people at a party, and we need to group them into $k$ non empty groups. Let us focus on a specific person. Call him Tony.

Suppose Tony is in a group by himself. How many ways are there to group the remaining $n$ people?

If Tony is not in a group by himself, how many groups can he join?

<details>
  <summary>__Solution__</summary>
  
  Case 1: If Tony is in a group by himself, then we have to break the remaining $n$ people into $k-1$ groups. This can be done in 
  $$
  \left\{
    \begin{array}{cc}
        n\\
        k-1
    \end{array}
  \right\}
  $$
  ways.
  
  Case 2: If Tony is not in a group by himself, then we first break up the remaining $n$ people into $k$ groups. Then, Tony can join any of them. The number of possible groups then is
  $$
  k\left\{
    \begin{array}{cc}
        n\\
        k
    \end{array}
  \right\}
  $$
  
  Case 1 and 2 together count the number of ways to break up $n+1$ people into $k$ non empty groups, which is precisely what the left side of the equation counts.
  
</details>

b.\ __Intuition__

Suppose we would like to break the $n+1$ guests into $k+1$ groups instead of $k$.

Tony wants to have $3$ people in his group. How many ways are there to select them?
For each such selection, how many ways are there to group the remaining people?

What is the largest number of people Tony can have in his group?

<details>
  <summary>__Solution__</summary>
  
  Say Tony wants to have $m$ in his group. That is to say he does not want $n-m$ people. These $n-m$ people must then be broken into $k$ groups. 
  
  The number of people Tony wants to join his group can range from $0$ to $n-k$. The reason for the upper bound is that at least $k$ people are required to make up the remaining $k$ groups.
  
  Taking the sum over the number of people in Tony's group we get
  $$\sum_{j=0}^{n-k}{n \choose j}\left\{
    \begin{array}{cc}
        n-j\\
        k
    \end{array}
  \right\}
  $$
  
  Now, instead of taking the sum over the number of people Tony wants in his group, we can equivalently take the sum over the number of people Tony does not want in his group. Hence,
  
  $$\sum_{j=0}^{n-k}{n \choose j}\left\{
      \begin{array}{cc}
          n-j\\
          k
      \end{array}
    \right\} = \sum_{i=n}^{k}{n \choose i}\left\{
      \begin{array}{cc}
          i\\
          k
      \end{array}
    \right\}
  $$
Since the sum counts all possible ways to group $n+1$ people into $k+1$ groups, we have 
$$
\sum_{i=n}^{k}{n \choose i}\left\{
      \begin{array}{cc}
          i\\
          k
      \end{array}
    \right\} = 
    \left\{
      \begin{array}{cc}
          n+1\\
          k+1
      \end{array}
    \right\}
$$
as desired.
</details>

###

a.\ __Intuition__

How many games are there in a round-robin tournament with $n+1$ participants?

What is wrong with the following line of thought? $3$ people participate in a round-robin tournament. Player $A$ participates in $2$ games. So do players $B$ and $C$. Hence, the total number of games in the tournament is $2 + 2 + 2 = 6$.

<details>
  <summary>__Solution__</summary>
  
  Let us count the number of games in a round-robin tournament with $n+1$ participants in two ways.
  
  Method 1: Since every player plays against all other players exactly once, the problem reduces to finding the number of ways to pair up $n+1$ people. There are ${n+1 \choose 2}$ ways to do so.
  
  Method 2: The first player participates in $n$ games. The second one also participates in $n$ games, but we have already counted the game against the first player, so we only care about $n-1$ games. The third player also participates in $n$ games, but we have already counted the games against the first and second players, so we only care about $n-2$ games. 
  
  In general, player $i$ will participate in $n+1-i$ games that we care about. Taking the sum over $i$ we get
  
  $$n + (n-1) + (n-2) + \dots + 2 + 1$$
  
  Since both methods count the same thing, they are equal.
  
</details>

b.\ __Intuition__

Consider the scenario hinted by the author.

If a person picks the number $7$, how many choices do they have for the next $3$ numbers? Can we generalize the result?

Now we consider the right side of the equation. Suppose the $3$ numbers a person has chosen with replacement are distinct, how many possible permutations are there? What if $2$ of the numbers are distinct? What if none of them are distinct?

<details>
  <summary>__Solution__</summary>
  
  LHS: If $n$ is chosen first, then the subsequent $3$ numbers can be any of $0, 1, \dots, n-1$. These $3$ numbers are chosen with replacement resulting in $n^{3}$ possibilities. Summing over possible values of $n$ we get $1^{3} + 2^{3} + \dots + n^{3}$ total number of possibilities.
  
  RHS: We can count the number of permutations of the $3$ numbers chosen with replacement from a different perspective. The $3$ numbers can either all be distinct, or all be the same, or differ in exactly $1$ value.
  
  Case 1: All $3$ numbers are distinct.
  
  Selecting $4$ (don't forget the very first, largest selected number) distinct numbers can be done in ${n+1 \choose 4}$ ways. The $3$ smaller numbers are free to permute amongst themselves. This gives us a total of $6{n+1 \choose 4}$ possibilities.
  
  Case 2: All $3$ numbers are the same.
  
  In this case, we have to select $2$ digits. The smaller digit will be sampled $3$ times and there are no ways to permute identical numbers, so the number of possiblities is ${n+1 \choose 2}$.
  
  Case 3: Two of the $3$ numbers are distinct.
  
  In this case, we have to select $3$ digits in total. One of the smaller $2$ digits will be sampled twice, giving us $3$ permutations. Since, there are $2$ choices for which digit gets sampled twice, we get a total of $6$ permutations. The total number of possibilities then is $6{n+1 \choose 3}$.
  
  Adding up the number of possibilities in each of the cases we get a total of $$6{n+1 \choose 4} + 6{n+1 \choose 3} + {n+1 \choose 2}$$ possibilities. 
  
  Since the LHS and the RHS count the same set, they are equal.
  
</details>

## Naive definition of probability

### 

__Intuition__

Suppose all three people are going to the same floor, how many choice are there?

What if only two of them are going to the same floor? What if they are all going to different floors?

<details>
  <summary>__Solution__</summary>
  
  Case 1: All three go to the same floor.

They can go to floors $2$ to $10$ for a total of $9$ choices.

Case 2: Two of them go to the same floor.

There are $9 \choose 2$ possibilities in this case.

Case 3: They all go to different floors.

There are $9 \choose 3$ possibilities in this case.

We are interested in the case of $3$ consecutive floors. There are $7$ equally likely possibilities $$(2, 3, 4), (3, 4, 5), (4, 5, 6), (5, 6, 7), (6, 7, 8), (7, 8, 9), (8, 9, 10).$$

Hence, the probability that the buttons for $3$ consecutive floors are pressed is $$\frac{7}{9 + {9 \choose 2} + {9 \choose 3}}$$

</details>
